name: Deploy to Azure

on:
  # add worflow dispatch to run manually
  workflow_dispatch:

  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: 'crudapp02183'
  AZURE_RESOURCE_GROUP: 'GitHub-Copilot-Challenges'
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, if different
  DOTNET_VERSION: '3.1.x' # set this to the .NET version you are using

jobs:
  deploy_resources:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure      
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy resources
      uses: azure/arm-deploy@v1
      with:      
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: deploy.json
        parameters: deploy.parameters.json
        deploymentMode: 'Incremental'
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy_application:
    needs: deploy_resources
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: |
        nuget restore '**/CRUD application 2.csproj'

    - name: Build and publish
      run: |
        msbuild /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile.pubxml

    - name: Login to Azure      
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: drop
        path: ./output
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./output