name: Deploy to Azure

on:
  # add worflow dispatch to run manually
  workflow_dispatch:

  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: 'crudapp02183'
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, if different
  DOTNET_VERSION: '3.1.x' # set this to the .NET version you are using

jobs:
  deploy_resources:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}         
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Deploy resources
      uses: azure/arm-deploy@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}         
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: deploy.json
        parameters: deploy.parameters.json

  deploy_application:
    needs: deploy_resources
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./output

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}         
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./output